# Test if your GPU is enabled

This is an auto-generated page. Run the commands below again to compare the results.

In [1]:
import sys

In [2]:
sys.version

'3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0]'

In [3]:
import os

In [4]:
os.system('uname -a')

Linux 5837113b8494 6.4.6-76060406-generic #202307241739~1692717645~22.04~5597803 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux


0

In [5]:
os.system('nvidia-smi')

Tue Sep  5 02:44:24 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:0C:00.0 Off |                  N/A |
| 35%   42C    P2              41W / 370W |    610MiB / 24576MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

0

In [6]:
os.system('nvcc --version')

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0


0

In [7]:
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [8]:
import tensorflow as tf

In [9]:
tf.__version__

'2.13.0'

In [10]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [11]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [12]:
tf.random.normal([3, 5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 1.286093  , -0.43535864,  0.644461  ,  0.17528243,  1.0025498 ],
       [ 0.5757749 , -0.38083574, -1.0074306 ,  0.10577042, -1.1193905 ],
       [-1.415574  ,  0.70957786,  0.4392282 , -1.1261785 ,  1.4041736 ]],
      dtype=float32)>

In [13]:
tf.reduce_sum(tf.random.normal([1000, 1000]))

<tf.Tensor: shape=(), dtype=float32, numpy=-378.9815>